name: Docker Push - Production

# Trigger the workflow on pushes to the 'dev' branch
on:
  push:
    branches:
      - main

# Define variables
env:
  docker_image_name: iqpr-report-export

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $docker_image_name:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag image
        run: docker tag $docker_image_name:latest ${{ secrets.DOCKERHUB_USERNAME }}/$docker_image_name:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$docker_image_name:latest
