name: Lint and Type Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_type_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pylint mypy

    - name: Run black
      run: |
        black --check src

    - name: Run pylint
      run: |
        pylint src

    - name: Run mypy
      run: |
        mypy src
